# Generated by Django 3.0.4 on 2020-03-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, unique=True, verbose_name='作者')),
                ('title', models.CharField(max_length=225, verbose_name='標題')),
                ('contnet', models.TextField(verbose_name='內文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='最後修改時間')),
            ],
            options={
                'verbose_name': '文章發布',
                'verbose_name_plural': '文章發布',
            },
        ),
    ]
