# Generated by Django 3.0.4 on 2020-03-26 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='標題')),
                ('content', models.TextField(blank=True, null=True, verbose_name='內文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章發布',
                'verbose_name_plural': '文章發布',
            },
        ),
    ]
