# Generated by Django 3.0.4 on 2020-03-21 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_create_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contnet',
            new_name='content',
        ),
    ]
